# Generated by Django 5.2.4 on 2026-07-13 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(blank=True, null=True, verbose_name='申请入党时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_records', to='imports.importbatch', verbose_name='来源导入批次')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_record', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '申请入党记录',
                'verbose_name_plural': '申请入党记录',
                'ordering': ['student__student_number'],
            },
        ),
        migrations.CreateModel(
            name='IdeologicalReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_total_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Excel填报总篇数')),
                ('calculated_date_count', models.PositiveIntegerField(default=0, verbose_name='系统计算日期数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_summaries', to='imports.importbatch', verbose_name='来源导入批次')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_summary', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '思想汇报汇总',
                'verbose_name_plural': '思想汇报汇总',
                'ordering': ['student__student_number'],
            },
        ),
        migrations.CreateModel(
            name='IdeologicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='思想汇报次数')),
                ('submitted_at', models.DateField(verbose_name='提交时间')),
                ('source_column_name', models.CharField(max_length=128, verbose_name='Excel来源列名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideological_reports', to='imports.importbatch', verbose_name='导入批次')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideological_reports', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '思想汇报明细',
                'verbose_name_plural': '思想汇报明细',
                'ordering': ['student__student_number', 'sequence_number'],
                'indexes': [models.Index(fields=['student', 'sequence_number'], name='materials_i_student_d62ba9_idx'), models.Index(fields=['submitted_at'], name='materials_i_submitt_58d65a_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'sequence_number', 'is_active'), name='unique_active_report_sequence')],
            },
        ),
    ]
