# Generated by Django 5.2.4 on 2026-07-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='支部名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='支部代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '党支部',
                'verbose_name_plural': '党支部',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('student_number', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('development_stage', models.CharField(choices=[('ACTIVIST', '入党积极分子'), ('PROBATIONARY', '中共预备党员'), ('FULL_MEMBER', '正式党员')], max_length=32, verbose_name='发展阶段')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='职务')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '无效')], default='active', max_length=16, verbose_name='学生状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.partybranch', verbose_name='党支部')),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='imports.importbatch', verbose_name='来源导入批次')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['student_number'],
                'indexes': [models.Index(fields=['name'], name='students_st_name_0bae46_idx'), models.Index(fields=['student_number'], name='students_st_student_0be38d_idx'), models.Index(fields=['development_stage'], name='students_st_develop_b3e025_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx')],
            },
        ),
    ]
