# Generated by Django 5.0 on 2026-08-08 03:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_ideologicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideologicalreport',
            name='submitted_at',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='提交时间'),
        ),
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(verbose_name='申请时间')),
                ('reported_total_count', models.IntegerField(blank=True, null=True, verbose_name='填报总篇数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_application_record', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '入党申请记录',
                'verbose_name_plural': '入党申请记录',
            },
        ),
    ]
