# Generated by Django 5.0 on 2026-08-07 08:44

import apps.students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_ideologicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideologicalreport',
            name='submitted_at',
            field=models.DateField(default=apps.students.models.get_default_submitted_date, verbose_name='提交时间'),
        ),
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(verbose_name='申请时间')),
                ('reported_total_count', models.IntegerField(default=0, verbose_name='填报总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_records', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '入党申请记录',
                'verbose_name_plural': '入党申请记录',
            },
        ),
    ]
