# Generated by Django 5.2.4 on 2026-07-13 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_role', models.CharField(blank=True, max_length=32, verbose_name='操作人角色')),
                ('action', models.CharField(max_length=64, verbose_name='操作')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='目标ID')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_opera_action_83eea1_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_opera_target__f440b1_idx')],
            },
        ),
    ]
