# Generated by Django 5.2.4 on 2026-07-13 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(max_length=128, verbose_name='批次标签')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('stored_file', models.FileField(blank=True, upload_to='imports/', verbose_name='保存文件')),
                ('file_hash', models.CharField(blank=True, max_length=128, verbose_name='文件哈希')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='导入时间')),
                ('status', models.CharField(choices=[('previewed', '已预览'), ('success', '成功'), ('failed', '失败'), ('rolled_back', '已回滚')], default='previewed', max_length=32, verbose_name='批次状态')),
                ('total_sheets', models.PositiveIntegerField(default=0, verbose_name='工作表总数')),
                ('success_sheets', models.PositiveIntegerField(default=0, verbose_name='成功工作表数')),
                ('failed_sheets', models.PositiveIntegerField(default=0, verbose_name='失败工作表数')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='成功行数')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='跳过行数')),
                ('warning_rows', models.PositiveIntegerField(default=0, verbose_name='警告行数')),
                ('created_students', models.PositiveIntegerField(default=0, verbose_name='新增学生数')),
                ('updated_students', models.PositiveIntegerField(default=0, verbose_name='更新学生数')),
                ('created_reports', models.PositiveIntegerField(default=0, verbose_name='新增思想汇报数')),
                ('updated_applications', models.PositiveIntegerField(default=0, verbose_name='更新申请记录数')),
                ('count_mismatch_rows', models.PositiveIntegerField(default=0, verbose_name='总篇数不一致行数')),
                ('unknown_branch_rows', models.PositiveIntegerField(default=0, verbose_name='未知支部行数')),
                ('invalid_stage_rows', models.PositiveIntegerField(default=0, verbose_name='无效阶段行数')),
                ('column_shift_rows', models.PositiveIntegerField(default=0, verbose_name='疑似列错位行数')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回滚时间')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_batches', to=settings.AUTH_USER_MODEL, verbose_name='回滚人')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportErrorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=128, verbose_name='工作表名称')),
                ('excel_row_number', models.PositiveIntegerField(verbose_name='Excel行号')),
                ('student_name', models.CharField(blank=True, max_length=64, verbose_name='学生姓名')),
                ('student_number', models.CharField(blank=True, max_length=32, verbose_name='学号')),
                ('field_name', models.CharField(blank=True, max_length=128, verbose_name='字段名')),
                ('error_code', models.CharField(max_length=64, verbose_name='错误代码')),
                ('error_message', models.TextField(verbose_name='错误说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_records', to='imports.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入错误',
                'verbose_name_plural': '导入错误',
                'ordering': ['import_batch_id', 'sheet_name', 'excel_row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportWarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=128, verbose_name='工作表名称')),
                ('excel_row_number', models.PositiveIntegerField(verbose_name='Excel行号')),
                ('student_name', models.CharField(blank=True, max_length=64, verbose_name='学生姓名')),
                ('student_number', models.CharField(blank=True, max_length=32, verbose_name='学号')),
                ('warning_code', models.CharField(max_length=64, verbose_name='警告代码')),
                ('warning_message', models.TextField(verbose_name='警告说明')),
                ('source_value', models.CharField(blank=True, max_length=255, verbose_name='原始值')),
                ('parsed_value', models.CharField(blank=True, max_length=255, verbose_name='解析值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_records', to='imports.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入警告',
                'verbose_name_plural': '导入警告',
                'ordering': ['import_batch_id', 'sheet_name', 'excel_row_number'],
            },
        ),
    ]
